//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyPost
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydbContext : DbContext
    {
        public mydbContext()
            : base("name=mydbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<images> images { get; set; }
        public virtual DbSet<platforms> platforms { get; set; }
        public virtual DbSet<posts> posts { get; set; }
        public virtual DbSet<preposts> preposts { get; set; }
        public virtual DbSet<program_categories> program_categories { get; set; }
        public virtual DbSet<programs> programs { get; set; }
        public virtual DbSet<spoilers> spoilers { get; set; }
        public virtual DbSet<tracker> tracker { get; set; }
    }
}
