//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyPost
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoundPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoundPost()
        {
            this.ReadyPost = new HashSet<ReadyPost>();
        }
    
        public int idFoundPost { get; set; }
        public string Name { get; set; }
        public string Uri { get; set; }
        public string Magnet { get; set; }
        public Nullable<System.DateTime> FoundedTime { get; set; }
        public int TorrentTracker_idTorrentTracker { get; set; }
    
        public virtual TorrentTracker TorrentTracker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadyPost> ReadyPost { get; set; }
    }
}
