//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyPost
{
    using System;
    using System.Collections.Generic;
    
    public partial class preposts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public preposts()
        {
            this.posts = new HashSet<posts>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string href { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> tracker { get; set; }
        public Nullable<sbyte> itpublic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<posts> posts { get; set; }
        public virtual tracker tracker1 { get; set; }
    }
}
