//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyPost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spoiler
    {
        public int idSpoiler { get; set; }
        public string Header { get; set; }
        public string Body { get; set; }
        public int ReadyPost_idReadyPost { get; set; }
    }
}
