//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyPostCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Img
    {
        public int idImg { get; set; }
        public string Uri { get; set; }
        public int TypeImg_idTypeImg { get; set; }
        public int ReadyPost_idReadyPost { get; set; }
    
        public virtual TypeImg TypeImg { get; set; }
    }
}
