//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyPostCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class TorrentSoftPost
    {
        public int idTorrentSoftPost { get; set; }
        public Nullable<System.DateTime> WasAdded { get; set; }
        public int ReadyPost_idReadyPost { get; set; }
    
        public virtual ReadyPost ReadyPost { get; set; }
    }
}
